// <auto-generated />
using System;
using AdeDl.BlazorApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdeDl.BlazorApp.Migrations
{
    [DbContext(typeof(AdeDlDbContext))]
    partial class AdeDlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("AdeDl.BlazorApp.Models.Database.Credential", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DelegationPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("AdeDl.BlazorApp.Models.Database.Customer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AdeDl.BlazorApp.Models.Operations.VersamentoGenerico", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceTributo1")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceTributo2")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceTributo3")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceTributo4")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Coobbligato")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Credito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoAddizionale")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PeriodFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PeriodTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeriodYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefisso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Versamenti");
                });

            modelBuilder.Entity("AdeDl.BlazorApp.Models.Database.Customer", b =>
                {
                    b.HasOne("AdeDl.BlazorApp.Models.Database.Credential", "Credential")
                        .WithMany("Customers")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("AdeDl.BlazorApp.Models.Database.Credential", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
